package tutorialINTERMEDIO;

public class Video6SUMA {
    //HEMOS PUESTO "PRIVAATE" YA QUE SOLO QUEREMOS QUE SE USEN DENTRO DE ESTA CLASE
    //HEMOS CREADO INTS PARA GUARDAR LOS VALORES ENVIADOS (VALOR1 Y VALOR2) SE GUARDEN EN ESTA CLASE

    private int vUno, vDos, Resultado;


    //AQUI HEMOS CREADO UN CONSTRUCTOR, DONDE LLAMAMOS Y GUARDAMOS A LOS VALORES INDICADOS.
    // ESOS VALORES (VALORUNO Y VALORDOS) LOS METEREMOS EN LOS NUEVOS NOMBRES(VUNO Y VDOS)

    public Video6SUMA(int valoruno, int valordos){

        //AQUI LES ASIGNAMOS SUS NUEVOS NOMBRES
        vUno = valoruno;
        vDos = valordos;
    }

    //CREAMOS UN METODO DONDE PERMITA REALIZAR LA SUMA. VOID NOS AYUDA A PODER INDICAR
    //A ESTE METODO QUE TIENE QUE RETORNAR UN VALOR, NOS TIENE QUE REGRESAR EL RESULTADO DE LA SUMA
    //SI NO USAMOS VOID, NO PODRA DEVOLVERNOS EL RESULTADO DE LA SUMA
    public void Operacion(){
        Resultado = vUno + vDos;
    }


        //CREAMOS OTRO METODO CON VOID, YA QUE QUEREMOS QUE NOS REGRESE UN VALOR
    public void Imprimir (){

        //AQUI LLAMAMOS A OPERACION YA QUE EL TIENE LE RESULTADO
        Operacion();
        //AQUI SOLO IMPRIMPOS EL RESULTADO
        System.out.println("El resultado es " +Resultado);
    }

}
